//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeevanjyothi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requirement
    {
        public int id { get; set; }
        public int userid { get; set; }
        public string requiredaddress { get; set; }
        public int bloodgroup { get; set; }
        public string requiredcity { get; set; }
        public System.DateTime requiredby { get; set; }
        public System.DateTime requestedon { get; set; }
        public string postFlag { get; set; }
    
        public virtual user user { get; set; }
    }
}
