//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeevanjyothi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class smsoutput
    {
        public int Id { get; set; }
        public string sentAction { get; set; }
        public string output { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public int actionid { get; set; }
    }
}
