//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeevanjyothi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.requirements = new HashSet<requirement>();
        }
    
        public int id { get; set; }
        public string fullname { get; set; }
        public long mobile { get; set; }
        public int bloodgroup { get; set; }
        public string password { get; set; }
        public string city { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<System.DateTime> lbd { get; set; }
        public System.DateTime createdate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual bloodgroup bloodgroup1 { get; set; }
        public virtual ICollection<requirement> requirements { get; set; }
    }
}
