//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeevanjyothi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vdonorslist
    {
        public string Name { get; set; }
        public long Mobile_No { get; set; }
        public string Blood_Group { get; set; }
        public string Donor_City { get; set; }
        public string Donor_Email { get; set; }
        public string Registered_Date { get; set; }
        public System.DateTime createdate { get; set; }
    }
}
